app/main_page_module/forms.py
# Import Form and RecaptchaField (optional)
from flask_wtf import FlaskForm # , RecaptchaField
from flask_wtf.file import FileField, MultipleFileField, FileAllowed, FileRequired

# Import Form elements such as TextField and BooleanField (optional)
from wtforms import BooleanField, IntegerField, StringField, TextAreaField, SelectField, \
     PasswordField, HiddenField, SubmitField, DateField, validators # BooleanField

# Import Form validators
from wtforms.validators import Email, EqualTo, ValidationError, InputRequired

from datetime import date


#email verification
import re
import os.path

from app.main_page_module.p_objects.dish import Dish
from app.main_page_module.p_objects.day_special_food import DaySpecialFood
from app.main_page_module.p_objects.ingredient import Ingredient



class DishForm(FlaskForm):    
    dish_ref_num = HiddenField('dish_ref_num', [validators.InputRequired(message='Dont fiddle around with the code!')])
    name = StringField('Ime', [validators.InputRequired(message='We need a name.'), validators.Length(max=150)])
    type_ = SelectField('Vrsta jedi:', [
        validators.InputRequired(message='You need to specify the main jed')], 
                         choices=[])    
    
    main_dish = SelectField(u'Ali je glavna jed?', [
        validators.InputRequired(message='You need to specify the time')], 
                         choices=[('1', 'Da'), ('0', 'Ne')])
    
    need_sidedish = SelectField(u'Potrebuje prilogo?', [
        validators.InputRequired(message='You need to specify the time')], 
                         choices=[('0', 'Ne'), ('1', 'Da')])      
    
    show_in_planner = SelectField(u'Naj se uporabi v avtomatski kalkulaciji?', [
        validators.InputRequired(message='You need to specify the time')], 
                         choices=[('1', 'Da'), ('0', 'Ne')])          
    
    
    
    submit = SubmitField('Dodaj Obrok')
    
    
    def __init__(self, *args, **kwargs):
        super(DishForm, self).__init__(*args, **kwargs)
        self.type_.choices = [[id_, name] for name, id_ in Dish.types().items()]


class MealForm(FlaskForm):    
    meal_date = DateField(
            'Datum obroka',
            validators=[InputRequired(message='We need a date.')],
            format='%Y-%m-%d',
            default=date.today
        )
    
    
    main_dish = SelectField('Glavna jed:', [
        validators.InputRequired(message='You need to specify the main jed')], 
                         choices=[])
    
    
    side_dish = SelectField('Priloga:', [
        validators.InputRequired(message='You need to specify the priloga')], 
                         choices=[('/', 'Brez')])
    
    keep = SelectField('Ohrani pri generiranju:', [
        validators.InputRequired(message='You need to specify if to keep')], 
                         choices=[('0', 'Ne'), ('1', 'Da')])
    
    
    submit = SubmitField('Dodaj Obrok')
    
    
    def __init__(self, *args, **kwargs):
        super(MealForm, self).__init__(*args, **kwargs)
        self.main_dish.choices = [[id_, data_["name"]] for id_, data_ in Dish.get_all(type_="1").items()]  
        self.side_dish.choices += [[id_, data_["name"]] for id_, data_ in Dish.get_all(type_="0").items()]    

class IngredientForm(FlaskForm):
    ingredient_ref_num = HiddenField('ingredient_ref_num', [validators.InputRequired(message='Dont fiddle around with the code!')])
    name = StringField('Ime', [validators.InputRequired(message='We need a name.'), validators.Length(max=150)])
    unit_type = SelectField('Enota:', [
        validators.InputRequired(message='You need to specify the unit type')], 
                         choices=[])
    
    submit = SubmitField('Shrani')
    
    def __init__(self, *args, **kwargs):
        super(IngredientForm, self).__init__(*args, **kwargs)
        self.unit_type.choices = [[id_, name] for id_, name in Ingredient.get_unit_types().items()]


class DishIngredientForm(FlaskForm):
    ingredient_ref_num = SelectField('Sestavina:', [
        validators.InputRequired(message='You need to select an ingredient')], 
                         choices=[])
    quantity = StringField('Količina', [validators.InputRequired(message='We need a quantity.'), validators.Length(max=50)])
    
    submit = SubmitField('Dodaj')
    
    def __init__(self, *args, **kwargs):
        super(DishIngredientForm, self).__init__(*args, **kwargs)
        # Get all ingredients and sort them alphabetically by name
        all_ingredients = Ingredient.get_all()
        sorted_ingredients = sorted(all_ingredients.items(), key=lambda x: x[1]["name"].lower())
        self.ingredient_ref_num.choices = [[id_, data_["name"] + " (" + data_.get("unit_type", "") + ")"] for id_, data_ in sorted_ingredients]


class DaySpecialFoodForm(FlaskForm):
    day_of_week = SelectField('Dan v tednu:', [
        validators.InputRequired(message='You need to specify the day of week')], 
                         choices=[
                             ('0', 'Ponedeljek'),
                             ('1', 'Torek'),
                             ('2', 'Sreda'),
                             ('3', 'Četrtek'),
                             ('4', 'Petek'),
                             ('5', 'Sobota'),
                             ('6', 'Nedelja')
                         ])
    
    main_dish = SelectField('Glavna jed:', [
        validators.InputRequired(message='You need to specify the main jed')], 
                         choices=[])
    
    side_dish = SelectField('Priloga:', 
                         choices=[('', 'Brez')])
    
    submit = SubmitField('Shrani')
    
    def __init__(self, *args, **kwargs):
        super(DaySpecialFoodForm, self).__init__(*args, **kwargs)
        self.main_dish.choices = [[id_, data_["name"]] for id_, data_ in Dish.get_all(type_="1").items()]  
        self.side_dish.choices += [[id_, data_["name"]] for id_, data_ in Dish.get_all(type_="0").items()]

class LoginForm(FlaskForm):
    username_or_email = StringField('Username or Email', [validators.InputRequired(message='Forgot your email address?')])
    password = PasswordField('Password', [validators.InputRequired(message='Must provide a password.')])
    remember = BooleanField()
    
    submit = SubmitField('Login')


 
form_dicts = {"Meal": MealForm,
              "Dish": DishForm,
              "Login": LoginForm,
              "DaySpecialFood": DaySpecialFoodForm,
              "Ingredient": IngredientForm,
              "DishIngredient": DishIngredientForm
              } 

app/main_page_module/controllers/controllers.py
import json

# Import flask dependencies
from flask import Blueprint, request, render_template, \
                  flash, g, session, redirect, url_for, jsonify, send_file, Response, abort

# Import module forms
from app.main_page_module.forms import form_dicts
#from app.main_page_module.p_objects.note_o import N_obj


from wrappers import login_required
from app.pylavor import Pylavor
from app.main_page_module.other import Randoms
from app.main_page_module.p_objects.meal import Meal
from app.main_page_module.p_objects.dish import Dish
from app.main_page_module.p_objects.day_special_food import DaySpecialFood
from app.main_page_module.p_objects.ingredient import Ingredient
from app.main_page_module.p_objects.dish_ingredient import DishIngredient


from app import app

#import os
import re
import os
import zipfile
import io
import pathlib
from passlib.hash import sha512_crypt
from datetime import datetime


# Define the blueprint: 'auth', set its url prefix: app.url/auth
main_page_module = Blueprint('main_page_module', __name__, url_prefix='/')


@app.context_processor
def inject_to_every_page():
    
    return dict(Randoms=Randoms, datetime=datetime, Pylavor=Pylavor,
                Dish=Dish, Meal=Meal, DaySpecialFood=DaySpecialFood,
                Ingredient=Ingredient, DishIngredient=DishIngredient)


@main_page_module.route('/', methods=['GET'])
def index():
    return render_template("main_page_module/index.html")

@main_page_module.route('/weekly_print', methods=['GET'])
def weekly_print():
    return render_template("main_page_module/weekly_print.html")

@main_page_module.route('/dishes/', methods=['GET'])
@login_required
def dishes():    
    return render_template("main_page_module/dishes/dishes_all.html")

@main_page_module.route('/dishes_new/', methods=['GET', 'POST'])
@login_required
def dishes_new():
    form = form_dicts["Dish"]()

    if form.validate_on_submit():
        dish_ref_num = Dish.new_id()
        
        dish_data = {"dish_ref_num": dish_ref_num,
            "name": form.name.data,
            "type_": form.type_.data,
            "main_dish": form.main_dish.data,
            "need_sidedish": form.need_sidedish.data,
            "show_in_planner": form.show_in_planner.data
            }

        dish = Dish(dish_data)
        
        try:
            dish.save()
            flash('Jed uspešno shranjena!', 'success')
            return redirect(url_for("main_page_module.dishes_view", dish_ref_num=dish_ref_num))
            
        except Exception as e:
            print(e)
            flash('Napaka pri shranjenju jedi!', 'error')        
        
    
    for error in form.errors:
        print(error)
        flash(f'Invalid Data: {error}', 'error')    

    return render_template("main_page_module/dishes/dishes_new.html", form=form)


@main_page_module.route('/dishes_view/<dish_ref_num>', methods=['GET'])
def dishes_view(dish_ref_num):
    dish_data = Dish.get_one(dish_ref_num)
    
    if dish_data is False:
        flash(f'Jed ne obstaja.', 'error')
        return redirect(url_for('main_page_module.dishes'))            
    
    dish = Dish(dish_data)
    
    return render_template("main_page_module/dishes/dishes_view.html", dish=dish)

@main_page_module.route('/dishes_edit/', methods=['POST'])
@main_page_module.route('/dishes_edit/<dish_ref_num>', methods=['GET', 'POST'])
@login_required
def dishes_edit(dish_ref_num:str=None):
    form = form_dicts["Dish"]()
    
    if dish_ref_num == None:
        dish_ref_num = form.dish_ref_num.data
    else:
        form.dish_ref_num.data = dish_ref_num
    
    dish_data = Dish.get_one(dish_ref_num)
    
    if dish_data is False:
        flash(f'Jed ne obstaja.', 'error')
        return redirect(url_for('main_page_module.dishes'))

    dish = Dish(dish_data)

    # GET
    if request.method == 'GET':
        form.process(dish_ref_num = dish_data["dish_ref_num"],
                     name = dish_data["name"],
                     type_ = dish_data["type_"],
                     main_dish = dish_data["main_dish"],
                     need_sidedish = dish_data["need_sidedish"],
                     show_in_planner = dish_data["show_in_planner"])
    
    # POST
    if form.validate_on_submit():
        dish_data = {"dish_ref_num": dish_ref_num,
            "name": form.name.data,
            "type_": form.type_.data,
            "main_dish": form.main_dish.data,
            "need_sidedish": form.need_sidedish.data,
            "show_in_planner": form.show_in_planner.data}
        
        dish = Dish(dish_data)

        try:
            dish.save()
            
            flash('Jed uspešno shranjena!', 'success')
            return redirect(url_for("main_page_module.dishes_view", dish_ref_num=dish_ref_num))
            
        except Exception as e:
            print(e)
            flash('Napaka pri shranjenju jedi!', 'error')
        
    
    for field, errors in form.errors.items():
        print(f'Field: {field}')
        for error in errors:
            flash(f'Invalid Data for {field}: {error}', 'error')
    
    
    return render_template("main_page_module/dishes/dishes_edit.html", form=form, dish=dish)



@main_page_module.route('/meals/', methods=['GET'])
@login_required
def meals():    
    return render_template("main_page_module/meals/meals_all.html")

@main_page_module.route('/meals_new/', methods=['GET', 'POST'])
@login_required
def meals_new():
    form = form_dicts["Meal"]()

    if form.validate_on_submit():
        meal_data = {"meal_date": str(form.meal_date.data),
            "main_dish": form.main_dish.data,
            "side_dish": form.side_dish.data,
            "keep": form.keep.data
            }
        meal = Meal(meal_data)
        
        try:
            meal.save()
            flash('Obrok uspešno shranjen!', 'success')
            return redirect(url_for("main_page_module.meals_view", meal_date=meal_date))
            
        except Exception as e:
            print(e)
            flash('Napaka pri shranjenju obroka!', 'error')        
        
    
    for error in form.errors:
        print(error)
        flash(f'Invalid Data: {error}', 'error')    

    return render_template("main_page_module/meals/meals_new.html", form=form)


@main_page_module.route('/meals_view/<meal_date>', methods=['GET'])
def meals_view(meal_date):
    meal_data = Meal.get_one(meal_date)
    
    if meal_data is False:
        flash(f'Obrok ne obstaja.', 'error')
        return redirect(url_for('main_page_module.meals'))            
    
    return render_template("main_page_module/meals/meals_view.html", meal=meal_data)


@main_page_module.route('/meals_edit/', methods=['POST'])
@main_page_module.route('/meals_edit/<meal_date>', methods=['GET', 'POST'])
@login_required
def meals_edit(meal_date:str=None):
    form = form_dicts["Meal"]()
    
    if meal_date == None:
        meal_date = form.meal_date.data
    else:
        form.meal_date.data = meal_date
    
    meal_data = Meal.get_one(meal_date)
    
    if meal_data is False:
        flash(f'Obrok ne obstaja.', 'error')
        return redirect(url_for('main_page_module.meals'))

    meal = Meal(meal_data)

    # GET
    if request.method == 'GET':
        form.process(meal_date = datetime.strptime(meal_data["meal_date"], "%Y-%m-%d").date(),
                     main_dish = meal_data["main_dish"],
                     side_dish = meal_data["side_dish"],
                     keep = meal_data.get("keep", "0"))
    
    # POST
    if form.validate_on_submit():
        meal_date = str(meal_date)
        meal_data = {"meal_date": meal_date,
            "main_dish": form.main_dish.data,
            "side_dish": form.side_dish.data,
            "keep": form.keep.data}
        
        meal = Meal(meal_data)

        try:
            meal.save()
            
            flash('Obrok uspešno shranjen!', 'success')
            return redirect(url_for("main_page_module.meals_view", meal_date=meal_date))
            
        except Exception as e:
            print(e)
            flash('Napaka pri shranjenju obroka!', 'error')
        
    
    for field, errors in form.errors.items():
        print(f'Field: {field}')
        for error in errors:
            flash(f'Invalid Data for {field}: {error}', 'error')
    
    
    return render_template("main_page_module/meals/meals_edit.html", form=form, meal=meal)


@main_page_module.route('/meals_randomize/<meal_date>/<index_>', methods=['GET'])
@main_page_module.route('/meals_randomize/<meal_date>', methods=['GET'])
def meals_randomize(meal_date, index_=False):
    meal_data = Meal.get_one(meal_date)
    
    if meal_data is False:
        flash(f'Obrok ne obstaja.', 'error')
        return redirect(url_for('main_page_module.meals'))            
    
    meal = Meal(meal_data)
    meal.randomize()
    
    if index_:
        return redirect(url_for("main_page_module.index"))
    else:
        return render_template("main_page_module/meals/meals_view.html", meal=meal)



@main_page_module.route('/generate_week/<week>', methods=['GET'])
@login_required
def generate_week(week):
    Meal.generate_week(week)
    
    return redirect(url_for("main_page_module.index"))



# Set the route and accepted methods
@main_page_module.route('/login/', methods=['GET', 'POST'])
def login():
    if ('user_id' in session):
        return redirect(url_for("main_page_module.index"))
    
    # If sign in form is submitted
    form = form_dicts["Login"]()

    # Verify the sign in form
    if form.validate_on_submit():
        admin_username = app.config['ADMIN_USERNAME']
        admin_password = app.config['ADMIN_PASS_HASH']
        
        # Generate the password hash
        same_pass = sha512_crypt.verify(form.password.data, admin_password)

        if not same_pass or admin_username != form.username_or_email.data:
            error_msg = "Login napačen."
            flash(error_msg, 'error')
            
        else:

app/templates/main_page_module/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="icon" type="image/png" href="{{ url_for('static', filename='favicon.ico') }}">


    <!-- Bootstrap CSS -->
    <link href="{{ url_for('static', filename='main_page_module/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- Bootstrap icons -->
    <link rel="stylesheet" href="{{ url_for('static', filename='main_page_module/icons/bootstrap_icons/bootstrap-icons.min.css') }}">
    
    <script src="{{ url_for('static', filename='main_page_module/jquerry/jquery-3.5.1.min.js') }}"></script>

    <style>
      /* Prevent horizontal overflow */
      html, body {
        overflow-x: hidden;
        max-width: 100%;
      }
      /* Ensure navbar toggler works on mobile */
      .navbar-toggler {
        border: none;
        padding: 0.25rem 0.5rem;
      }
      .navbar-toggler:focus {
        box-shadow: none;
      }
      /* Active nav link styling */
      .navbar-nav .nav-link.active,
      .navbar-nav .nav-link.text-secondary {
        color: rgba(255, 255, 255, 0.75) !important;
        font-weight: 500;
      }
      /* Mobile menu improvements */
      @media (max-width: 991.98px) {
        .navbar-collapse {
          margin-top: 1rem;
          padding-top: 1rem;
          border-top: 1px solid rgba(255, 255, 255, 0.1);
        }
        .navbar-nav .nav-link {
          padding: 0.5rem 0;
        }
      }
    </style>

    {% block extraheader %}
    {% endblock extraheader %}

    <title>{{ config['APP_NAME'] }}</title>
  </head>


  <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="bootstrap" viewBox="0 0 118 94">
      <title>{{ config['APP_NAME'] }}</title>
      <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>
    </symbol>
  </svg>
    
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand d-flex align-items-center" href="/">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap" style="fill: rgb(235, 235, 235); "><use xlink:href="#bootstrap"></use></svg>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link {% block nav_index %}{% endblock nav_index %}" href="{{ url_for('main_page_module.index') }}">
                <i class="bi bi-house"></i> <span class="d-lg-inline">Domov</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% block nav_v_obr %}{% endblock nav_v_obr %}" href="{{ url_for('main_page_module.meals') }}">
                <i class="bi bi-basket"></i> <span class="d-lg-inline">Vsi obroki</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% block nav_v_jedi %}{% endblock nav_v_jedi %}" href="{{ url_for('main_page_module.dishes') }}">
                <i class="bi bi-backpack2"></i> <span class="d-lg-inline">Vse jedi</span>
              </a>
            </li>
            {% if session['user_id'] %}
            <li class="nav-item">
              <a class="nav-link {% block nav_ingredients %}{% endblock nav_ingredients %}" href="{{ url_for('main_page_module.ingredients') }}">
                <i class="bi bi-list-ul"></i> <span class="d-lg-inline">Sestavine</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% block nav_day_special %}{% endblock nav_day_special %}" href="{{ url_for('main_page_module.day_special_foods') }}">
                <i class="bi bi-calendar-event"></i> <span class="d-lg-inline">Posebne jedi</span>
              </a>
            </li>
            {% endif %}
          </ul>
          <div class="d-flex">
            {% if session['user_id'] %}
              <a class="btn btn-outline-light" href="{{ url_for('main_page_module.logout') }}">
                <i class="bi bi-box-arrow-right"></i> Logout
              </a>
            {% else %}
              <a class="btn btn-outline-light" href="{{ url_for('main_page_module.login') }}">
                <i class="bi bi-box-arrow-in-right"></i> Login
              </a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        <div>
          {% for category, message in messages %}
            {% if category == "error" %}
              <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            {% else %}
              <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            {% endif %}
          {% endfor %}
        </div>
      {% endif %}
    {% endwith %}

    {% block content %}
    {% endblock %}

    <br>
    <hr>
    <footer class="footer mt-auto py-3 bg-body-tertiary text-center">
      <div class="container">
        <span class="text-body-secondary">&copy; 2025 - <script>document.write(new Date().getFullYear())</script> <a href="{{ url_for('main_page_module.login') }}">{{ config['APP_NAME'] }}</a></span>
      </div>
    </footer>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Bootstrap JS -->
    <script src="{{ url_for('static', filename='main_page_module/bootstrap/js/bootstrap.bundle.min.js') }}"></script>


  </body>
</html>

app/templates/main_page_module/chopping_list.html
{% extends "main_page_module/base.html" %}

{% block extraheader %}
{% endblock extraheader  %}

{% block nav_index %}text-secondary{% endblock nav_index %}

{% block content%}

  <div class="container-fluid" >
    <br>
    
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url_for('main_page_module.index') }}">Domov</a></li>
        <li class="breadcrumb-item active" aria-current="page">Seznam sestavin za {% if week == 0 %}ta teden{% else %}naslednji teden{% endif %}</li>
      </ol>
    </nav>
    
    <div class="row">
      <div class="col-sm-1">
      </div>
      
      <div class="col-sm-10">
        <legend>Seznam sestavin za {% if week == 0 %}ta teden{% else %}naslednji teden{% endif %}</legend>
        
        {% if ingredients_dict %}
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>Sestavina</th>
                <th>Enota</th>
                <th>Količine</th>
              </tr>
            </thead>
            <tbody>
              {% for ingredient_ref_num, data in ingredients_dict.items() %}
                <tr>
                  <td><b>{{ data['ingredient']['name'] }}</b></td>
                  <td>{{ data['ingredient']['unit_type'] }}</td>
                  <td>{{ data['total_quantity'] }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        {% else %}
          <p class="text-muted">Ni sestavin za ta teden.</p>
        {% endif %}
        
        <div class="mt-3">
          <a class="btn btn-outline-secondary" href="{{ url_for('main_page_module.index') }}" role="button">Nazaj</a>
          <a class="btn btn-outline-primary" href="{{ url_for('main_page_module.chopping_list', week=0) }}" role="button">Ta teden</a>
          <a class="btn btn-outline-primary" href="{{ url_for('main_page_module.chopping_list', week=1) }}" role="button">Naslednji teden</a>
        </div>
      </div>

      <div class="col-sm-1">
      </div>
    </div>
  </div>

{% endblock content %}