app/main_page_module/forms.py
# Import Form and RecaptchaField (optional)
from flask_wtf import FlaskForm # , RecaptchaField
from flask_wtf.file import FileField, MultipleFileField, FileAllowed, FileRequired

# Import Form elements such as TextField and BooleanField (optional)
from wtforms import BooleanField, IntegerField, StringField, TextAreaField, SelectField, \
     PasswordField, HiddenField, SubmitField, DateField, validators # BooleanField

# Import Form validators
from wtforms.validators import Email, EqualTo, ValidationError, InputRequired

from datetime import date


#email verification
import re
import os.path

from app.main_page_module.p_objects.dish import Dish
from app.main_page_module.p_objects.day_special_food import DaySpecialFood
from app.main_page_module.p_objects.ingredient import Ingredient



class DishForm(FlaskForm):    
    dish_ref_num = HiddenField('dish_ref_num', [validators.InputRequired(message='Dont fiddle around with the code!')])
    name = StringField('Ime', [validators.InputRequired(message='We need a name.'), validators.Length(max=150)])
    type_ = SelectField('Vrsta jedi:', [
        validators.InputRequired(message='You need to specify the main jed')], 
                         choices=[])    
    
    main_dish = SelectField(u'Ali je glavna jed?', [
        validators.InputRequired(message='You need to specify the time')], 
                         choices=[('1', 'Da'), ('0', 'Ne')])
    
    need_sidedish = SelectField(u'Potrebuje prilogo?', [
        validators.InputRequired(message='You need to specify the time')], 
                         choices=[('0', 'Ne'), ('1', 'Da')])      
    
    show_in_planner = SelectField(u'Naj se uporabi v avtomatski kalkulaciji?', [
        validators.InputRequired(message='You need to specify the time')], 
                         choices=[('1', 'Da'), ('0', 'Ne')])          
    
    
    
    submit = SubmitField('Dodaj Obrok')
    
    
    def __init__(self, *args, **kwargs):
        super(DishForm, self).__init__(*args, **kwargs)
        self.type_.choices = [[id_, name] for name, id_ in Dish.types().items()]


class MealForm(FlaskForm):    
    meal_date = DateField(
            'Datum obroka',
            validators=[InputRequired(message='We need a date.')],
            format='%Y-%m-%d',
            default=date.today
        )
    
    
    main_dish = SelectField('Glavna jed:', [
        validators.InputRequired(message='You need to specify the main jed')], 
                         choices=[])
    
    
    side_dish = SelectField('Priloga:', [
        validators.InputRequired(message='You need to specify the priloga')], 
                         choices=[('/', 'Brez')])
    
    keep = SelectField('Ohrani pri generiranju:', [
        validators.InputRequired(message='You need to specify if to keep')], 
                         choices=[('0', 'Ne'), ('1', 'Da')])
    
    
    submit = SubmitField('Dodaj Obrok')
    
    
    def __init__(self, *args, **kwargs):
        super(MealForm, self).__init__(*args, **kwargs)
        self.main_dish.choices = [[id_, data_["name"]] for id_, data_ in Dish.get_all(type_="1").items()]  
        self.side_dish.choices += [[id_, data_["name"]] for id_, data_ in Dish.get_all(type_="0").items()]    

class IngredientForm(FlaskForm):
    ingredient_ref_num = HiddenField('ingredient_ref_num', [validators.InputRequired(message='Dont fiddle around with the code!')])
    name = StringField('Ime', [validators.InputRequired(message='We need a name.'), validators.Length(max=150)])
    unit_type = SelectField('Enota:', [
        validators.InputRequired(message='You need to specify the unit type')], 
                         choices=[])
    
    submit = SubmitField('Shrani')
    
    def __init__(self, *args, **kwargs):
        super(IngredientForm, self).__init__(*args, **kwargs)
        self.unit_type.choices = [[id_, name] for id_, name in Ingredient.get_unit_types().items()]


class DishIngredientForm(FlaskForm):
    ingredient_ref_num = SelectField('Sestavina:', [
        validators.InputRequired(message='You need to select an ingredient')], 
                         choices=[])
    quantity = StringField('Količina', [validators.InputRequired(message='We need a quantity.'), validators.Length(max=50)])
    
    submit = SubmitField('Dodaj')
    
    def __init__(self, *args, **kwargs):
        super(DishIngredientForm, self).__init__(*args, **kwargs)
        # Get all ingredients and sort them alphabetically by name
        all_ingredients = Ingredient.get_all()
        sorted_ingredients = sorted(all_ingredients.items(), key=lambda x: x[1]["name"].lower())
        self.ingredient_ref_num.choices = [[id_, data_["name"] + " (" + data_.get("unit_type", "") + ")"] for id_, data_ in sorted_ingredients]


class DaySpecialFoodForm(FlaskForm):
    day_of_week = SelectField('Dan v tednu:', [
        validators.InputRequired(message='You need to specify the day of week')], 
                         choices=[
                             ('0', 'Ponedeljek'),
                             ('1', 'Torek'),
                             ('2', 'Sreda'),
                             ('3', 'Četrtek'),
                             ('4', 'Petek'),
                             ('5', 'Sobota'),
                             ('6', 'Nedelja')
                         ])
    
    main_dish = SelectField('Glavna jed:', [
        validators.InputRequired(message='You need to specify the main jed')], 
                         choices=[])
    
    side_dish = SelectField('Priloga:', 
                         choices=[('', 'Brez')])
    
    submit = SubmitField('Shrani')
    
    def __init__(self, *args, **kwargs):
        super(DaySpecialFoodForm, self).__init__(*args, **kwargs)
        self.main_dish.choices = [[id_, data_["name"]] for id_, data_ in Dish.get_all(type_="1").items()]  
        self.side_dish.choices += [[id_, data_["name"]] for id_, data_ in Dish.get_all(type_="0").items()]

class LoginForm(FlaskForm):
    username_or_email = StringField('Username or Email', [validators.InputRequired(message='Forgot your email address?')])
    password = PasswordField('Password', [validators.InputRequired(message='Must provide a password.')])
    remember = BooleanField()
    
    submit = SubmitField('Login')


 
form_dicts = {"Meal": MealForm,
              "Dish": DishForm,
              "Login": LoginForm,
              "DaySpecialFood": DaySpecialFoodForm,
              "Ingredient": IngredientForm,
              "DishIngredient": DishIngredientForm
              } 

app/main_page_module/controllers/controllers.py
import json

# Import flask dependencies
from flask import Blueprint, request, render_template, \
                  flash, g, session, redirect, url_for, jsonify, send_file, Response, abort

# Import module forms
from app.main_page_module.forms import form_dicts
#from app.main_page_module.p_objects.note_o import N_obj


from wrappers import login_required
from app.pylavor import Pylavor
from app.main_page_module.other import Randoms
from app.main_page_module.p_objects.meal import Meal
from app.main_page_module.p_objects.dish import Dish
from app.main_page_module.p_objects.day_special_food import DaySpecialFood
from app.main_page_module.p_objects.ingredient import Ingredient
from app.main_page_module.p_objects.dish_ingredient import DishIngredient


from app import app

#import os
import re
import os
import zipfile
import io
import pathlib
from passlib.hash import sha512_crypt
from datetime import datetime


# Define the blueprint: 'auth', set its url prefix: app.url/auth
main_page_module = Blueprint('main_page_module', __name__, url_prefix='/')


@app.context_processor
def inject_to_every_page():
    
    return dict(Randoms=Randoms, datetime=datetime, Pylavor=Pylavor,
                Dish=Dish, Meal=Meal, DaySpecialFood=DaySpecialFood,
                Ingredient=Ingredient, DishIngredient=DishIngredient)


@main_page_module.route('/', methods=['GET'])
def index():
    return render_template("main_page_module/index.html")

@main_page_module.route('/weekly_print', methods=['GET'])
def weekly_print():
    return render_template("main_page_module/weekly_print.html")

@main_page_module.route('/dishes/', methods=['GET'])
@login_required
def dishes():    
    return render_template("main_page_module/dishes/dishes_all.html")

@main_page_module.route('/dishes_new/', methods=['GET', 'POST'])
@login_required
def dishes_new():
    form = form_dicts["Dish"]()

    if form.validate_on_submit():
        dish_ref_num = Dish.new_id()
        
        dish_data = {"dish_ref_num": dish_ref_num,
            "name": form.name.data,
            "type_": form.type_.data,
            "main_dish": form.main_dish.data,
            "need_sidedish": form.need_sidedish.data,
            "show_in_planner": form.show_in_planner.data
            }

        dish = Dish(dish_data)
        
        try:
            dish.save()
            flash('Jed uspešno shranjena!', 'success')
            return redirect(url_for("main_page_module.dishes_view", dish_ref_num=dish_ref_num))
            
        except Exception as e:
            print(e)
            flash('Napaka pri shranjenju jedi!', 'error')        
        
    
    for error in form.errors:
        print(error)
        flash(f'Invalid Data: {error}', 'error')    

    return render_template("main_page_module/dishes/dishes_new.html", form=form)


@main_page_module.route('/dishes_view/<dish_ref_num>', methods=['GET'])
def dishes_view(dish_ref_num):
    dish_data = Dish.get_one(dish_ref_num)
    
    if dish_data is False:
        flash(f'Jed ne obstaja.', 'error')
        return redirect(url_for('main_page_module.dishes'))            
    
    dish = Dish(dish_data)
    
    return render_template("main_page_module/dishes/dishes_view.html", dish=dish)

@main_page_module.route('/dishes_edit/', methods=['POST'])
@main_page_module.route('/dishes_edit/<dish_ref_num>', methods=['GET', 'POST'])
@login_required
def dishes_edit(dish_ref_num:str=None):
    form = form_dicts["Dish"]()
    
    if dish_ref_num == None:
        dish_ref_num = form.dish_ref_num.data
    else:
        form.dish_ref_num.data = dish_ref_num
    
    dish_data = Dish.get_one(dish_ref_num)
    
    if dish_data is False:
        flash(f'Jed ne obstaja.', 'error')
        return redirect(url_for('main_page_module.dishes'))

    dish = Dish(dish_data)

    # GET
    if request.method == 'GET':
        form.process(dish_ref_num = dish_data["dish_ref_num"],
                     name = dish_data["name"],
                     type_ = dish_data["type_"],
                     main_dish = dish_data["main_dish"],
                     need_sidedish = dish_data["need_sidedish"],
                     show_in_planner = dish_data["show_in_planner"])
    
    # POST
    if form.validate_on_submit():
        dish_data = {"dish_ref_num": dish_ref_num,
            "name": form.name.data,
            "type_": form.type_.data,
            "main_dish": form.main_dish.data,
            "need_sidedish": form.need_sidedish.data,
            "show_in_planner": form.show_in_planner.data}
        
        dish = Dish(dish_data)

        try:
            dish.save()
            
            flash('Jed uspešno shranjena!', 'success')
            return redirect(url_for("main_page_module.dishes_view", dish_ref_num=dish_ref_num))
            
        except Exception as e:
            print(e)
            flash('Napaka pri shranjenju jedi!', 'error')
        
    
    for field, errors in form.errors.items():
        print(f'Field: {field}')
        for error in errors:
            flash(f'Invalid Data for {field}: {error}', 'error')
    
    
    return render_template("main_page_module/dishes/dishes_edit.html", form=form, dish=dish)



@main_page_module.route('/meals/', methods=['GET'])
@login_required
def meals():    
    return render_template("main_page_module/meals/meals_all.html")

@main_page_module.route('/meals_new/', methods=['GET', 'POST'])
@login_required
def meals_new():
    form = form_dicts["Meal"]()

    if form.validate_on_submit():
        meal_data = {"meal_date": str(form.meal_date.data),
            "main_dish": form.main_dish.data,
            "side_dish": form.side_dish.data,
            "keep": form.keep.data
            }
        meal = Meal(meal_data)
        
        try:
            meal.save()
            flash('Obrok uspešno shranjen!', 'success')
            return redirect(url_for("main_page_module.meals_view", meal_date=meal_date))
            
        except Exception as e:
            print(e)
            flash('Napaka pri shranjenju obroka!', 'error')        
        
    
    for error in form.errors:
        print(error)
        flash(f'Invalid Data: {error}', 'error')    

    return render_template("main_page_module/meals/meals_new.html", form=form)


@main_page_module.route('/meals_view/<meal_date>', methods=['GET'])
def meals_view(meal_date):
    meal_data = Meal.get_one(meal_date)
    
    if meal_data is False:
        flash(f'Obrok ne obstaja.', 'error')
        return redirect(url_for('main_page_module.meals'))            
    
    return render_template("main_page_module/meals/meals_view.html", meal=meal_data)


@main_page_module.route('/meals_edit/', methods=['POST'])
@main_page_module.route('/meals_edit/<meal_date>', methods=['GET', 'POST'])
@login_required
def meals_edit(meal_date:str=None):
    form = form_dicts["Meal"]()
    
    if meal_date == None:
        meal_date = form.meal_date.data
    else:
        form.meal_date.data = meal_date
    
    meal_data = Meal.get_one(meal_date)
    
    if meal_data is False:
        flash(f'Obrok ne obstaja.', 'error')
        return redirect(url_for('main_page_module.meals'))

    meal = Meal(meal_data)

    # GET
    if request.method == 'GET':
        form.process(meal_date = datetime.strptime(meal_data["meal_date"], "%Y-%m-%d").date(),
                     main_dish = meal_data["main_dish"],
                     side_dish = meal_data["side_dish"],
                     keep = meal_data.get("keep", "0"))
    
    # POST
    if form.validate_on_submit():
        meal_date = str(meal_date)
        meal_data = {"meal_date": meal_date,
            "main_dish": form.main_dish.data,
            "side_dish": form.side_dish.data,
            "keep": form.keep.data}
        
        meal = Meal(meal_data)

        try:
            meal.save()
            
            flash('Obrok uspešno shranjen!', 'success')
            return redirect(url_for("main_page_module.meals_view", meal_date=meal_date))
            
        except Exception as e:
            print(e)
            flash('Napaka pri shranjenju obroka!', 'error')
        
    
    for field, errors in form.errors.items():
        print(f'Field: {field}')
        for error in errors:
            flash(f'Invalid Data for {field}: {error}', 'error')
    
    
    return render_template("main_page_module/meals/meals_edit.html", form=form, meal=meal)


@main_page_module.route('/meals_randomize/<meal_date>/<index_>', methods=['GET'])
@main_page_module.route('/meals_randomize/<meal_date>', methods=['GET'])
def meals_randomize(meal_date, index_=False):
    meal_data = Meal.get_one(meal_date)
    
    if meal_data is False:
        flash(f'Obrok ne obstaja.', 'error')
        return redirect(url_for('main_page_module.meals'))            
    
    meal = Meal(meal_data)
    meal.randomize()
    
    if index_:
        return redirect(url_for("main_page_module.index"))
    else:
        return render_template("main_page_module/meals/meals_view.html", meal=meal)



@main_page_module.route('/generate_week/<week>', methods=['GET'])
@login_required
def generate_week(week):
    Meal.generate_week(week)
    
    return redirect(url_for("main_page_module.index"))



# Set the route and accepted methods
@main_page_module.route('/login/', methods=['GET', 'POST'])
def login():
    if ('user_id' in session):
        return redirect(url_for("main_page_module.index"))
    
    # If sign in form is submitted
    form = form_dicts["Login"]()

    # Verify the sign in form
    if form.validate_on_submit():
        admin_username = app.config['ADMIN_USERNAME']
        admin_password = app.config['ADMIN_PASS_HASH']
        
        # Generate the password hash
        same_pass = sha512_crypt.verify(form.password.data, admin_password)

        if not same_pass or admin_username != form.username_or_email.data:
            error_msg = "Login napačen."
            flash(error_msg, 'error')
            
        else:

app/templates/main_page_module/dishes/dishes_all.html
{% extends "main_page_module/base.html" %}

{% block extraheader %}
<link href="//cdn.datatables.net/2.1.8/css/dataTables.dataTables.min.css" rel="stylesheet">

{% endblock extraheader  %}

{% block nav_freist %}text-secondary{% endblock nav_freist %}



{% block content%}

  <div class="container-fluid" >
    <br>
    
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="">Vsi Artifakti</a></li>
      </ol>
    </nav>
    
    <div class="row">
      <div class="col-sm-1">

      </div>
      
      
      <div class="col-sm-7">
        <legend>Obroki</legend> 
        
        <table id="meals_table" class="table table-bordered" style="width:100%">
          <thead>
              <tr>
                  <th>Ime</th>
                  <th>Tip</th>
                  <th>Glavna jed</th>
                  <th>Potrebuje prilogo</th>
                  <th>Uporabljena pri kalkulaciji</th>
                  <th>*</th>
              </tr>
          </thead>
          <tbody>
            {% for dish_ref_num, data in Dish.get_all().items() %}
            {% set dish = Dish(data) %}
              <tr>
                  <td>{{ dish.name }}</td>
                  <td><span class="badge text-bg-light">{{ Dish.types(dish.type_) }}</span></td>
                  <td><span class="badge text-bg-light">{{ Dish.yes_no(dish.main_dish) }}</span></td>
                  <td><span class="badge text-bg-light">{{ Dish.yes_no(dish.need_sidedish) }}</span></td>
                  <td><span class="badge text-bg-light">{{ Dish.yes_no(dish.show_in_planner) }}</span></td>
                  <td><a class="btn btn-outline-primary" href="{{ url_for('main_page_module.dishes_view', dish_ref_num=dish_ref_num) }}" role="button">Preglej</a></td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
        
      </div>


        
      <div class="col-sm-4">
        <img src="{{ url_for('static', filename='artifacts/placeholder_vector.svg') }}" class="img-fluid" alt="...">
        <hr>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
        <hr>
        <div class="d-grid gap-2">
          <div class="btn-group" role="group">
            {% if session['user_id'] %}<a class="btn btn-primary" href="{{ url_for('main_page_module.dishes_new') }}" role="button">Dodaj nov obrok</a>{% endif %}
          </div>
        </div>
      </div>

 
      </div>
    </div>

  </div>

  
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  <script src="//cdn.datatables.net/2.1.8/js/dataTables.min.js"></script>

  <script>
    let table = new DataTable('#meals_table');
  </script>

{% endblock content %}

app/templates/main_page_module/dishes/dishes_edit.html
{% extends "main_page_module/base.html" %}

{% block extraheader %}
<link href="https://cdn.jsdelivr.net/npm/summernote@0.9.0/dist/summernote.min.css" rel="stylesheet">
{% endblock extraheader  %}

{% block nav_freist %}text-secondary{% endblock nav_freist %}

{% macro render_field(field, placeholder=None) %}
  <div class="mb-3">
      {% set css_class = 'form-control ' + kwargs.pop('class', '') %}

      {{ field.label }}

      {% if field.errors %}
          {% set css_class = css_class + ' is-invalid' %}

          {% for error in field.errors %}
              
              <small id="{{ field.label.text }}" class="text-danger">
                  {{ error }}
            </small>

          {% endfor %}
          </ul>
      {% endif %}

      {{ field(class=css_class, autocomplete="off", placeholder=placeholder, **kwargs) }}
  </div>
{% endmacro %}


{% block content%}

  <div class="container-fluid" >
    <br>
    
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url_for('main_page_module.dishes') }}">Vse Jedi</a></li>
        <li class="breadcrumb-item active" aria-current="page"><a href="{{ url_for('main_page_module.dishes_view', dish_ref_num=form.dish_ref_num.data) }}">Jed</a></li>
        <li class="breadcrumb-item active" aria-current="page">Uredi Jed {{form.dish_ref_num.data}}</li>
      </ol>
    </nav>
        
    <div class="row">
      <div class="col-sm-2">
        
      </div>
      
      
      <div class="col-sm-8">

        <form method="POST" action="{{ url_for('main_page_module.dishes_edit') }}" accept-charset="UTF-8" role="form" enctype="multipart/form-data">
          {{ form.csrf_token }}
          {{ form.dish_ref_num }}
  
          {{ render_field(form.name, placeholder="Ime Jedi", autofocus="") }}


          <div class="row">
            <div class="col-sm-3">
              {{ render_field(form.type_, class="form-select") }}
            </div>
            <div class="col-sm-3">
              {{ render_field(form.main_dish, class="form-select") }}
            </div>
            <div class="col-sm-3">
              {{ render_field(form.need_sidedish, class="form-select") }}
            </div>
            <div class="col-sm-3">
              {{ render_field(form.show_in_planner, class="form-select") }}
            </div>
          </div>


 

          {{ form.submit(class="form-control btn btn-dark mb-2", value="Uredi") }}


        </form>

      </div>

 
      </div>
    </div>

  </div>

{% endblock content %}

app/templates/main_page_module/dishes/dishes_new.html
{% extends "main_page_module/base.html" %}

{% block extraheader %}
<link href="https://cdn.jsdelivr.net/npm/summernote@0.9.0/dist/summernote.min.css" rel="stylesheet">
{% endblock extraheader  %}

{% block nav_freist %}text-secondary{% endblock nav_freist %}

{% macro render_field(field, placeholder=None) %}
  <div class="mb-3">
      {% set css_class = 'form-control ' + kwargs.pop('class', '') %}

      {{ field.label }}

      {% if field.errors %}
          {% set css_class = css_class + ' is-invalid' %}

          {% for error in field.errors %}
              
              <small id="{{ field.label.text }}" class="text-danger">
                  {{ error }}
            </small>

          {% endfor %}
          </ul>
      {% endif %}

      {{ field(class=css_class, autocomplete="off", placeholder=placeholder, **kwargs) }}
  </div>
{% endmacro %}


{% block content%}

  <div class="container-fluid" >
    <br>
    
    <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ url_for('main_page_module.dishes') }}">Vse Jedi</a></li>
            <li class="breadcrumb-item active" aria-current="page">Nova Jed</li>
          </ol>
        </nav>
        
    <div class="row">
      <div class="col-sm-2">
        
      </div>
      
      
      <div class="col-sm-8">

        <form method="POST" action="{{ url_for('main_page_module.dishes_new') }}" accept-charset="UTF-8" role="form" enctype="multipart/form-data">
          {{ form.csrf_token }}

          <input type="hidden" id="dish_ref_num" name="dish_ref_num" value="999">
  
          {{ render_field(form.name, placeholder="Ime Jedi", autofocus="") }}

          

          <div class="row">
            <div class="col-sm-3">
              {{ render_field(form.type_, class="form-select") }}
            </div>
            <div class="col-sm-3">
              {{ render_field(form.main_dish, class="form-select") }}
            </div>
            <div class="col-sm-3">
              {{ render_field(form.need_sidedish, class="form-select") }}
            </div>
            <div class="col-sm-3">
              {{ render_field(form.show_in_planner, class="form-select") }}
            </div>
          </div>

          {{ form.submit(class="form-control btn btn-dark mb-2", value="Ustvari") }}


        </form>

      </div>


        
      <div class="col-sm-2">

      </div>

 
      </div>
    </div>

  </div>

{% endblock content %}

app/templates/main_page_module/dishes/dishes_view.html
{% extends "main_page_module/base.html" %}

{% block extraheader %}
<link href="https://cdn.jsdelivr.net/npm/summernote@0.9.0/dist/summernote.min.css" rel="stylesheet">
{% endblock extraheader  %}

{% block nav_freist %}text-secondary{% endblock nav_freist %}

{% macro render_field(field, placeholder=None) %}
  <div class="mb-3">
      {% set css_class = 'form-control ' + kwargs.pop('class', '') %}

      {{ field.label }}

      {% if field.errors %}
          {% set css_class = css_class + ' is-invalid' %}

          {% for error in field.errors %}
              
              <small id="{{ field.label.text }}" class="text-danger">
                  {{ error }}
            </small>

          {% endfor %}
          </ul>
      {% endif %}

      {{ field(class=css_class, autocomplete="off", placeholder=placeholder, **kwargs) }}
  </div>
{% endmacro %}


{% block content%}

  <div class="container-fluid" >
    <br>
    
    <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ url_for('main_page_module.dishes') }}">Vse Jedi</a></li>
            <li class="breadcrumb-item active" aria-current="page">Artifakt <span class="badge text-bg-dark">{{dish["dish_ref_num"]}}</span></li>
          </ol>
        </nav>
        
    <div class="row">
      <div class="col-sm-1">
        <a class="btn btn-outline-primary" href="{{ url_for('main_page_module.dishes_edit', dish_ref_num=dish['dish_ref_num']) }}" role="button">Uredi</a>
      </div>
      
      
      
      
      <div class="col-sm-10">              
        <div class="row">
          <div class="col-sm-6">

            <table class="table">
              <tbody>
                <tr>
                  <th scope="row">Ime</th>
                  <td><b>{{dish["name"]}}</b></td>
                </tr>
                <tr>
                  <th scope="row">Tip</th>
                  <td><span class="badge text-bg-dark">{{ Dish.types(dish["type_"])}}</span></td>
                </tr>
                <tr>
                  <th scope="row">Ali je glavna jed</th>
                  <td><span class="badge text-bg-warning">{{ Dish.yes_no(dish["main_dish"]) }}</span></td>
                </tr>
                <tr>
                  <th scope="row">Potrebuje Prilogo</th>
                  <td><span class="badge text-bg-secondary">{{ Dish.yes_no(dish["need_sidedish"])}}</span></td>
                </tr>
                <tr>
                  <th scope="row">Ali se uporabi pri kalkulaciji</th>
                  <td><span class="badge text-bg-primary">{{ Dish.yes_no(dish["show_in_planner"])}}</span></td>
                </tr>
                
              </tbody>
            </table>

              <h4>Sestavine</h4>
            {% set dish_ingredients = DishIngredient.get_for_dish(dish['dish_ref_num']) %}
            {% if dish_ingredients %}
              <ul class="list-group mb-3">
                {% for di in dish_ingredients %}
                  {% set ingredient = Ingredient.get_one(di['ingredient_ref_num']) %}
                  {% if ingredient %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                      <span>{{ ingredient['name'] }} - {{ di['quantity'] }} {{ ingredient.get('unit_type', '') }}</span>
                      {% if session['user_id'] %}
                        <a class="btn btn-outline-danger btn-sm" href="{{ url_for('main_page_module.dish_ingredients_delete', dish_ref_num=dish['dish_ref_num'], ingredient_ref_num=di['ingredient_ref_num']) }}" role="button" onclick="return confirm('Ali ste prepričani, da želite izbrisati sestavino?')">Izbriši</a>
                      {% endif %}
                    </li>
                  {% endif %}
                {% endfor %}
              </ul>
            {% else %}
              <p class="text-muted">Ni sestavin.</p>
            {% endif %}
            {% if session['user_id'] %}
              <a class="btn btn-primary" href="{{ url_for('main_page_module.dish_ingredients_add', dish_ref_num=dish['dish_ref_num']) }}" role="button">Dodaj sestavino</a>
            {% endif %}

          </div>

          <div class="col-sm-6">

            <div id="carouselExample" class="carousel slide">
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img src="{{ url_for('static', filename='artifacts/placeholder_vector.svg') }}" class="d-block w-100" alt="...">
                </div>
              </div>
              <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
              </button>
            </div>
            
          </div>
        </div>


      </div>



        
      <div class="col-sm-1">

      </div>

 
      </div>
    </div>

  </div>


{% endblock content %}